---
all:
  hosts:
    nextcloudtarget:
      ansible_host: "{{ hostname }}"
      ansible_user: "{{ username }}"
#      ansible_ssh_private_key_file: ~/.ssh/example
#      ansible_port: 2222
      ansible_become_pass: "{{ targetpw }}"

# ssh_private_key_file is not needed if using ssh-copy-id 
# ansible_port is only needed if not 22 