version: "3.5"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
{% if traefikuser != "" %}
      - --api.dashboard=true
{% endif %}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:{{ httpport }}
      - --entrypoints.websecure.address=:{{ httpsport }}
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email={{ email }}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    restart: always 
    ports:
      - {{ httpport }}:80
      - {{ httpsport }}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
{% if traefikuser != "" %}
      # Dashboard
      - traefik.http.routers.dashboard.rule=Host(`{{ traefikhost}}.{{ domain }}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.dashboard.middlewares=dashboardauth
      - traefik.http.middlewares.dashboardauth.basicauth.users={{ traefikcreds.stdout }}
{% endif %}
      # HTTPS Redirect
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - nextcloud

networks:
  nextcloud:
    name: nextcloud-external
