version: "3.5"

services:

  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-basename=mariadblog
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{ mysqlrootpw }}
      - MYSQL_PASSWORD={{ mysqlpw }}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER={{ mysqlusr }}
    networks:
      - nextcloud-internal

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    networks:
      - nextcloud-internal

  cron:
    container_name: nextcloud-cron
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    networks:
      - nextcloud-internal

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=nextcloud-external
      - traefik.http.routers.nextcloud.rule=Host(`{{ nextcloudhost }}.{{ domain }}`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls.certresolver=letsencrypt
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect
      - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' {{ domain }} *.{{ domain }}
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
    environment:
      - MYSQL_PASSWORD={{ mysqlpw }}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER={{ mysqlusr }}
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS={{ nextcloudhost }}.{{ domain }}
      - TRUSTED_PROXIES=172.18.0.0/16
    networks:
      - nextcloud-external
      - nextcloud-internal

volumes:
  db:

networks:
  nextcloud-external:
    external: 
      name: nextcloud-external
  nextcloud-internal:
      internal: true 